### ISSUE TITLE
As a fellow /[py|rb|node|php]env/ user you may like anyenv

### ISSUE THREAD

**Issue by ruevaughn** [grigoryvp/dotfiles#3]
I stumbled across your dotfiles and was able to pull some useful things so this is an attempt to try and help in return. You may want to consider using [anyenv](https://anyenv.github.io/), though since you have this automated you might not actually find it very useful. In case you do decide to give it a try here is what I run to get it going

https://github.com/grigoryvp/dotfiles/blob/c2b0dec7cc761c298024b8abf7fed10265122e42/configure_macos.sh#L200

**Comment by grigoryvp** [comment]
Thanks for a tip! There are lots of attempts like now to replace the pyenv/rbenv/nodenv trinity, i'm watching them closely, especially the "asdf" manager. Hope they will settle to something less shell-y and universal in a few years 😇

**Comment by ruevaughn** [comment]
Cool, i'll check those out as well!
